### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by MarcinV** [reneboer/python-carnet-client#1]
Hi,

I am getting below error. Any idea about the reason?

pi@hassbian:~ $ python /home/homeassistant/.homeassistant/scripts/vw_carnet_rb1.py retrieveCarNetInfo
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/scripts/vw_carnet_rb1.py", line 206, in <module>
    url = CarNetLogin(s,CARNET_USERNAME,CARNET_PASSWORD)
  File "/home/homeassistant/.homeassistant/scripts/vw_carnet_rb1.py", line 103, in CarNetLogin
    ref_url = extract_redirect_url(r).replace('&amp;', '&')
  File "/home/homeassistant/.homeassistant/scripts/vw_carnet_rb1.py", line 41, in extract_redirect_url
    return redurl_re.search(r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by reneboer** [comment]
Hi @MarcinV 
For some reason the login fails. Have you put in your user id and pwd in the top of the script?
You can add a line 101 to see what the message is.
print(r.text)

**Comment by MarcinV** [comment]
:-(, that was the mistake of me, sorry for that. Now it is working well!
